### ISSUE TITLE
dimension issue

### ISSUE THREAD

**Issue by ranery** [zhuchen03/VIBNet#1]
When I try to run the first provided command, there is dimension problem shown up as:

````
RuntimeError: The size of tensor a (64) must match the size of tensor b (3) at non-singleton dimension 3
````

The complete error information:

````
python ib_vgg_train.py --gpu 0 --batch-norm --resume-vgg-pt baseline/cifar10/checkpoint_299_nocrop.tar --ban-crop --opt adam --cfg D4 --epochs 300 --lr 1.4e-3 --weight-decay 5e-5 --kl-fac 1.4e-5 --save-dir ib_vgg_chk/D4
Namespace(ban_crop=True, ban_flip=False, batch_norm=True, batchsize=128, cfg='D4', data_set='cifar10', epochs=300, gpu=0, ib_lr=-1, ib_wd=-1, init_var=0.01, kl_fac=1.4e-05, lr=0.0014, lr_epoch=30, lr_fac=0.5, mag=9, momentum=0.9, no_ib=False, opt='adam', print_freq=50, reg_weight=0, resume='', resume_vgg_pt='baseline/cifar10/checkpoint_299_nocrop.tar', resume_vgg_vib='', sample_test=0, sample_train=1, save_dir='ib_vgg_chk/D4', tb_path='tb_ib_vgg', threshold=0, val=False, weight_decay=5e-05, workers=1)
Files already downloaded and verified
Using structure [(64, 0.03125), (64, 0.03125), 'M', (128, 0.0625), (128, 0.0625), 'M', (256, 0.125), (256, 0.125), (256, 0.125), 'M', (512, 0.25), (512, 0.25), (512, 0.25), 'M', (512, 0.5), (512, 0.5), (512, 0.5), 'M']
detected VIB params (45): ['conv_layers.3.prior_z_logD', 'conv_layers.3.post_z_mu', 'conv_layers.3.post_z_logD', 'conv_layers.7.prior_z_logD', 'conv_layers.7.post_z_mu', 'conv_layers.7.post_z_logD', 'conv_layers.12.prior_z_logD', 'conv_layers.12.post_z_mu', 'conv_layers.12.post_z_logD', 'conv_layers.16.prior_z_logD', 'conv_layers.16.post_z_mu', 'conv_layers.16.post_z_logD', 'conv_layers.21.prior_z_logD', 'conv_layers.21.post_z_mu', 'conv_layers.21.post_z_logD', 'conv_layers.25.prior_z_logD', 'conv_layers.25.post_z_mu', 'conv_layers.25.post_z_logD', 'conv_layers.29.prior_z_logD', 'conv_layers.29.post_z_mu', 'conv_layers.29.post_z_logD', 'conv_layers.34.prior_z_logD', 'conv_layers.34.post_z_mu', 'conv_layers.34.post_z_logD', 'conv_layers.38.prior_z_logD', 'conv_layers.38.post_z_mu', 'conv_layers.38.post_z_logD', 'conv_layers.42.prior_z_logD', 'conv_layers.42.post_z_mu', 'conv_layers.42.post_z_logD', 'conv_layers.47.prior_z_logD', 'conv_layers.47.post_z_mu', 'conv_layers.47.post_z_logD', 'conv_layers.51.prior_z_logD', 'conv_layers.51.post_z_mu', 'conv_layers.51.post_z_logD', 'conv_layers.55.prior_z_logD', 'conv_layers.55.post_z_mu', 'conv_layers.55.post_z_logD', 'fc_layers.2.prior_z_logD', 'fc_layers.2.post_z_mu', 'fc_layers.2.post_z_logD', 'fc_layers.5.prior_z_logD', 'fc_layers.5.post_z_mu', 'fc_layers.5.post_z_logD']
detected VGG params (58): ['conv_layers.0.weight', 'conv_layers.0.bias', 'conv_layers.1.weight', 'conv_layers.1.bias', 'conv_layers.4.weight', 'conv_layers.4.bias', 'conv_layers.5.weight', 'conv_layers.5.bias', 'conv_layers.9.weight', 'conv_layers.9.bias', 'conv_layers.10.weight', 'conv_layers.10.bias', 'conv_layers.13.weight', 'conv_layers.13.bias', 'conv_layers.14.weight', 'conv_layers.14.bias', 'conv_layers.18.weight', 'conv_layers.18.bias', 'conv_layers.19.weight', 'conv_layers.19.bias', 'conv_layers.22.weight', 'conv_layers.22.bias', 'conv_layers.23.weight', 'conv_layers.23.bias', 'conv_layers.26.weight', 'conv_layers.26.bias', 'conv_layers.27.weight', 'conv_layers.27.bias', 'conv_layers.31.weight', 'conv_layers.31.bias', 'conv_layers.32.weight', 'conv_layers.32.bias', 'conv_layers.35.weight', 'conv_layers.35.bias', 'conv_layers.36.weight', 'conv_layers.36.bias', 'conv_layers.39.weight', 'conv_layers.39.bias', 'conv_layers.40.weight', 'conv_layers.40.bias', 'conv_layers.44.weight', 'conv_layers.44.bias', 'conv_layers.45.weight', 'conv_layers.45.bias', 'conv_layers.48.weight', 'conv_layers.48.bias', 'conv_layers.49.weight', 'conv_layers.49.bias', 'conv_layers.52.weight', 'conv_layers.52.bias', 'conv_layers.53.weight', 'conv_layers.53.bias', 'fc_layers.0.weight', 'fc_layers.0.bias', 'fc_layers.3.weight', 'fc_layers.3.bias', 'fc_layers.6.weight', 'fc_layers.6.bias']
Learning rate of IB: 0.0014, learning rate of others: 0.0014
loaded pretraind model with acc 91.94
Traceback (most recent call last):
  File "ib_vgg_train.py", line 395, in <module>
    main()
  File "ib_vgg_train.py", line 104, in main
    model.state_dict()[ib_keys[i*9+j]].copy_(state_dict['state_dict'][vgg_keys[i*6+j]])
RuntimeError: The size of tensor a (64) must match the size of tensor b (3) at non-singleton dimension 3

````

**Comment by zhuchen03** [comment]
Try out my new code. It's an issue with the latest version of PyTorch, where the BN layers have an extra "num_batches_tracked" state. Please try and see if you can still re-produce the results with the latest version of PyTorch, thanks!

**Comment by ranery** [comment]
It solve my problem, thanks!

**Comment by ranery** [comment]
Hi, I encountered another error:
````
Traceback (most recent call last):
  File "ib_vgg_train.py", line 399, in <module>
    main()
  File "ib_vgg_train.py", line 126, in main
    model.state_dict()[ib_keys[ib_offset + i*5 + j]].copy_(state_dict['state_dict'][vgg_keys[ib_offset + i*5 + j]])
IndexError: list index out of range
````
When I try to run:
````
 python ib_vgg_train.py --data-set cifar10 --gpu 0 --batch-norm --resume-vgg-vib baseline/cifar10/D6_600/last_epoch.pth --opt adam --cfg D6 --epochs 300 --lr 1e-3 --weight-decay 5e-5 --kl-fac 3e-5 --save-dir ib_vgg_chk/D6_600
````
Wait for your help, thanks!

**Comment by zhuchen03** [comment]
Just fixed again. Pull and try it.

**Comment by ranery** [comment]
It works, and the last issue about given scripts:
````
python ib_vgg_train.py --data-set cifar10 --gpu 0 --batch-norm --resume-vgg-vib baseline/cifar10/G5_400/last_epoch.pth --opt adam --cfg G5 --epochs 300 --lr 1e-3 --weight-decay 5E-5 --kl-fac 1e-5 --save-dir ib_vgg_chk/G5-400
````
Error information:
````
Traceback (most recent call last):
  File "ib_vgg_train.py", line 400, in <module>
    main()
  File "ib_vgg_train.py", line 127, in main
    model.state_dict()[ib_keys[ib_offset + i*5 + j]].copy_(state_dict['state_dict'][vgg_keys[vgg_group_size*13 + i*5 + j]])
RuntimeError: output with shape [] doesn't match the broadcast shape [512]
````

**Comment by zhuchen03** [comment]
Done. Didn't expect so many compatibility issues. Now the rules are even more complicated. Be careful when playing with it.

**Comment by ranery** [comment]
Sure, thanks! I am also wondering can training of IB directly without baseline parameter also produces similar performance if so, it will be a piece of great news to me.

**Comment by ranery** [comment]
Thanks, I have no extra questions
